Repository prgrms-web-devcourse-final-project/WEB1_1_ZeroOne_BE, pull requests merged in 2024-12, with the labels that each got.

#58 #55 - 아키이브 관련 API 구현
  src/main/java/com/palettee/archive/controller/ArchiveController.java
  src/main/java/com/palettee/archive/controller/dto/request/ArchiveRegisterRequest.java
  src/main/java/com/palettee/archive/controller/dto/request/ArchiveUpdateRequest.java
  src/main/java/com/palettee/archive/controller/dto/request/CommentUpdateRequest.java
  src/main/java/com/palettee/archive/controller/dto/response/ArchiveDetailResponse.java
  src/main/java/com/palettee/archive/controller/dto/response/CommentDetail.java
  src/main/java/com/palettee/archive/domain/Archive.java
  src/main/java/com/palettee/archive/domain/Comment.java
  src/main/java/com/palettee/archive/repository/ArchiveCustomRepository.java
  src/main/java/com/palettee/archive/repository/ArchiveCustomRepositoryImpl.java
  src/main/java/com/palettee/archive/service/ArchiveService.java
  src/main/java/com/palettee/archive/service/CommentService.java
  src/main/java/com/palettee/notification/service/NotificationService.java
  src/test/java/com/palettee/archive/ArchiveServiceTest.java
  src/test/java/com/palettee/archive/CommentServiceTest.java
  src/test/java/com/palettee/user/controller/UserControllerTest.java
  src/test/java/com/palettee/user/service/UserServiceTest.java
Labels: 📌 feature

#56 `[Hotfix]` - 유저 정보 수정 시 `LazyInitializationException` 문제 해결
  src/main/java/com/palettee/user/repository/UserRepository.java
  src/main/java/com/palettee/user/service/BasicRegisterService.java
  src/main/java/com/palettee/user/service/UserService.java
Labels: 🐞 bug, ⛏ fix

#57 `[Feat]` - 간단한 유저 `report` 기능 추가
  src/main/java/com/palettee/archive/repository/ArchiveCustomRepository.java
  src/main/java/com/palettee/archive/repository/ArchiveCustomRepositoryImpl.java
  src/main/java/com/palettee/gathering/repository/GatheringRepositoryCustom.java
  src/main/java/com/palettee/gathering/repository/GatheringRepositoryImpl.java
  src/main/java/com/palettee/global/configs/SecurityConfig.java
  src/main/java/com/palettee/global/exception/ErrorCode.java
  src/main/java/com/palettee/global/security/jwt/controllers/TokenController.java
  src/main/java/com/palettee/user/controller/BasicRegisterController.java
  src/main/java/com/palettee/user/controller/ReportController.java
  src/main/java/com/palettee/user/controller/UserController.java
  src/main/java/com/palettee/user/controller/dto/request/reports/RegisterReportCommentRequest.java
  src/main/java/com/palettee/user/controller/dto/request/reports/RegisterReportRequest.java
  src/main/java/com/palettee/user/controller/dto/request/users/EditUserInfoRequest.java
  src/main/java/com/palettee/user/controller/dto/request/users/RegisterBasicInfoRequest.java
  src/main/java/com/palettee/user/controller/dto/request/users/RegisterPortfolioRequest.java
  src/main/java/com/palettee/user/controller/dto/response/reports/ReportCommentListResponse.java
  src/main/java/com/palettee/user/controller/dto/response/reports/ReportCommentResponse.java
  src/main/java/com/palettee/user/controller/dto/response/reports/ReportDetailResponse.java
  src/main/java/com/palettee/user/controller/dto/response/reports/ReportListResponse.java
  src/main/java/com/palettee/user/controller/dto/response/reports/ReportResponse.java
  src/main/java/com/palettee/user/controller/dto/response/reports/SimpleReportCommentResponse.java
  src/main/java/com/palettee/user/controller/dto/response/reports/SimpleReportResponse.java
  src/main/java/com/palettee/user/controller/dto/response/users/BasicInfoResponse.java
  src/main/java/com/palettee/user/controller/dto/response/users/GetUserArchiveResponse.java
  src/main/java/com/palettee/user/controller/dto/response/users/GetUserGatheringResponse.java
  src/main/java/com/palettee/user/controller/dto/response/users/SimpleArchiveInfo.java
  src/main/java/com/palettee/user/controller/dto/response/users/SimpleGatheringInfo.java
  src/main/java/com/palettee/user/controller/dto/response/users/UserDetailResponse.java
  src/main/java/com/palettee/user/controller/dto/response/users/UserEditFormResponse.java
  src/main/java/com/palettee/user/controller/dto/response/users/UserResponse.java
  src/main/java/com/palettee/user/domain/Report.java
  src/main/java/com/palettee/user/domain/ReportComment.java
  src/main/java/com/palettee/user/domain/ReportType.java
  src/main/java/com/palettee/user/domain/User.java
  src/main/java/com/palettee/user/exception/InvalidDivisionException.java
  src/main/java/com/palettee/user/exception/InvalidJobGroupException.java
  src/main/java/com/palettee/user/exception/InvalidReportTypeException.java
  src/main/java/com/palettee/user/exception/JobGroupMismatchException.java
  src/main/java/com/palettee/user/exception/NotOwnUserException.java
  src/main/java/com/palettee/user/exception/ReportNotFoundException.java
  src/main/java/com/palettee/user/exception/UserAccessException.java
  src/main/java/com/palettee/user/exception/UserNotFoundException.java
  src/main/java/com/palettee/user/repository/CustomReportRepository.java
  src/main/java/com/palettee/user/repository/CustomReportRepositoryImpl.java
  src/main/java/com/palettee/user/repository/ReportCommentRepository.java
  src/main/java/com/palettee/user/repository/ReportRepository.java
  src/main/java/com/palettee/user/service/BasicRegisterService.java
  src/main/java/com/palettee/user/service/ReportService.java
  src/main/java/com/palettee/user/service/UserService.java
  src/test/java/com/palettee/user/controller/BasicRegisterControllerTest.java
  src/test/java/com/palettee/user/controller/ReportControllerTest.java
  src/test/java/com/palettee/user/controller/UserControllerTest.java
  src/test/java/com/palettee/user/service/BasicRegisterServiceTest.java
  src/test/java/com/palettee/user/service/ReportServiceTest.java
  src/test/java/com/palettee/user/service/UserServiceTest.java
Labels: 📌 feature, 📂 refactor

#63 #62 - 모니터링 설정
  build.gradle
  src/main/java/com/palettee/global/configs/SecurityConfig.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: ✨ enhancement

#67 `EC2` / `local` 에서 `OAuth 2` redirect-uri 분리
  src/main/resources/application-local.yml
Labels: ✨ enhancement

#70 fix: `EC2` / `local` 에서 `OAuth 2` 로그인 성공 redirect-uri 분리
  src/main/java/com/palettee/global/security/oauth/handler/OAuth2LoginSuccessHandler.java
  src/main/resources/application-local.yml
  src/test/resources/application.yml
Labels: ⛏ fix

#72 #71 - 아카이브 관련 잘못된 로직 수정
  src/main/java/com/palettee/archive/controller/ArchiveController.java
  src/main/java/com/palettee/archive/controller/dto/response/ArchiveDetailResponse.java
  src/main/java/com/palettee/archive/repository/ArchiveCustomRepositoryImpl.java
  src/main/java/com/palettee/global/configs/SecurityConfig.java
Labels: 🐞 bug

#77 #68 - `[Feat/Enhance]` : 사소한 `User` API 추가 및 도메인 요청별 `log` 저장 기능 추가
  src/main/java/com/palettee/global/exception/GlobalExceptionHandler.java
  src/main/java/com/palettee/global/logging/DomainType.java
  src/main/java/com/palettee/global/logging/MDCLoggingFilter.java
  src/main/java/com/palettee/user/controller/UserController.java
  src/main/java/com/palettee/user/controller/dto/response/users/SimpleUserResponse.java
  src/main/java/com/palettee/user/service/UserService.java
  src/main/resources/application-local.yml
  src/main/resources/logback-appender.xml
  src/main/resources/logback-spring.xml
  src/test/java/com/palettee/user/controller/UserControllerTest.java
  src/test/java/com/palettee/user/service/UserServiceTest.java
  src/test/resources/application.yml
Labels: 📌 feature, ✨ enhancement

#81 `[Fix]` - `log` 형식 개선, 간단한 `AOP` 추가
  src/main/java/com/palettee/archive/controller/dto/request/ArchiveRegisterRequest.java
  src/main/java/com/palettee/archive/controller/dto/request/ArchiveUpdateRequest.java
  src/main/java/com/palettee/archive/controller/dto/request/CommentUpdateRequest.java
  src/main/java/com/palettee/archive/controller/dto/request/CommentWriteRequest.java
  src/main/java/com/palettee/global/aop/PerformanceAspect.java
  src/main/java/com/palettee/global/logging/MDCLoggingFilter.java
  src/main/java/com/palettee/global/security/jwt/filters/JwtExceptionHandlingFilter.java
  src/main/java/com/palettee/global/security/oauth/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/palettee/user/controller/dto/request/users/EditUserInfoRequest.java
  src/main/java/com/palettee/user/controller/dto/request/users/RegisterBasicInfoRequest.java
  src/main/resources/application-local.yml
  src/main/resources/logback-appender.xml
  src/main/resources/logback-spring.xml
  src/test/resources/application.yml
Labels: ⛏ fix, ✨ enhancement

#83 #80 - 아카이브 관련 오류 사항 수정 및 임시 로직 구현
  src/main/java/com/palettee/archive/controller/ArchiveController.java
  src/main/java/com/palettee/archive/controller/dto/response/ArchiveDetailResponse.java
  src/main/java/com/palettee/archive/controller/dto/response/ArchiveListResponse.java
  src/main/java/com/palettee/archive/controller/dto/response/ArchiveSimpleResponse.java
  src/main/java/com/palettee/archive/controller/dto/response/CommentDetail.java
  src/main/java/com/palettee/archive/exception/NotArchiveOwner.java
  src/main/java/com/palettee/archive/repository/ArchiveImageRepository.java
  src/main/java/com/palettee/archive/repository/ArchiveRepository.java
  src/main/java/com/palettee/archive/repository/TagRepository.java
  src/main/java/com/palettee/archive/service/ArchiveService.java
  src/main/java/com/palettee/archive/service/CommentService.java
  src/main/java/com/palettee/global/configs/SecurityConfig.java
  src/main/java/com/palettee/global/exception/ErrorCode.java
  src/main/java/com/palettee/global/security/validation/UserUtils.java
  src/main/java/com/palettee/likes/repository/LikeRepository.java
  src/main/resources/application-local.yml
  src/test/java/com/palettee/archive/ArchiveServiceTest.java
Labels: 🐞 bug, 📌 feature

#90 #89 - 진입점 로깅 추가
  src/main/java/com/palettee/global/aop/querycounter/ConnectionHandler.java
  src/main/java/com/palettee/global/aop/querycounter/PerformanceAspect.java
  src/main/java/com/palettee/global/aop/querycounter/QueryCounter.java
  src/main/java/com/palettee/global/aop/tracer/LogAspect.java
  src/main/java/com/palettee/global/aop/tracer/LogTracer.java
  src/main/java/com/palettee/global/aop/tracer/TraceId.java
  src/main/java/com/palettee/global/aop/tracer/TraceStatus.java
Labels: 📑 documentation, ✨ enhancement

#92 #91 - 슬랙 알림 구현
  build.gradle
  src/main/java/com/palettee/global/configs/SlackLogAppenderConfig.java
  src/main/java/com/palettee/global/configs/ThreadPoolConfig.java
  src/main/java/com/palettee/global/exception/GlobalExceptionHandler.java
  src/main/java/com/palettee/global/slack/RequestInfo.java
  src/main/java/com/palettee/global/slack/SlackNotification.java
  src/main/java/com/palettee/global/slack/SlackNotificationAspect.java
  src/main/resources/application-local.yml
  src/test/resources/application.yml
Labels: ✨ enhancement

#93 Fix/trivial things
  src/main/java/com/palettee/global/exception/GlobalExceptionHandler.java
  src/main/java/com/palettee/global/security/jwt/filters/JwtExceptionHandlingFilter.java
  src/main/java/com/palettee/global/security/oauth/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/palettee/user/controller/dto/response/users/SimpleGatheringInfo.java
  src/main/java/com/palettee/user/domain/User.java
  src/main/java/com/palettee/user/service/UserService.java
  src/main/resources/application-local.yml
  src/test/java/com/palettee/archive/CommentServiceTest.java
  src/test/java/com/palettee/chat/ChatServiceTest.java
  src/test/java/com/palettee/gathering/service/GatheringServiceTest.java
  src/test/java/com/palettee/global/security/jwt/controllers/TokenControllerTest.java
  src/test/java/com/palettee/global/security/jwt/services/TokenServiceTest.java
  src/test/java/com/palettee/portfolio/service/PortFolioServiceTest.java
  src/test/java/com/palettee/user/service/UserServiceTest.java
Labels: ⛏ fix, ✨ enhancement

#84 #51 - Redis zset 사용하여 조회 성능 개선
  src/main/java/com/palettee/chat/controller/ChatController.java
  src/main/java/com/palettee/chat/controller/dto/request/ChatImgUrlRequest.java
  src/main/java/com/palettee/chat/controller/dto/request/ChatRequest.java
  src/main/java/com/palettee/chat/controller/dto/response/ChatCustomResponse.java
  src/main/java/com/palettee/chat/controller/dto/response/ChatImgUrl.java
  src/main/java/com/palettee/chat/controller/dto/response/ChatImgUrlResponse.java
  src/main/java/com/palettee/chat/controller/dto/response/ChatResponse.java
  src/main/java/com/palettee/chat/domain/Chat.java
  src/main/java/com/palettee/chat/repository/ChatCustomRepository.java
  src/main/java/com/palettee/chat/repository/ChatCustomRepositoryImpl.java
  src/main/java/com/palettee/chat/repository/ChatJdbcRepository.java
  src/main/java/com/palettee/chat/repository/ChatRepository.java
  src/main/java/com/palettee/chat/service/ChatRedisService.java
  src/main/java/com/palettee/chat/service/ChatService.java
  src/main/java/com/palettee/chat/service/ChatWriteBackScheduling.java
  src/main/java/com/palettee/chat/service/dto/ChatImageSaveDto.java
  src/main/java/com/palettee/chat/service/dto/ChatSaveDto.java
  src/main/java/com/palettee/chat_room/controller/ChatRoomController.java
  src/main/java/com/palettee/chat_room/domain/ChatRoom.java
  src/main/java/com/palettee/global/configs/RedisConfig.java
  src/main/java/com/palettee/global/redis/pub/RedisPublisher.java
  src/main/java/com/palettee/global/redis/sub/RedisSubscriber.java
  src/main/java/com/palettee/global/redis/utils/TypeConverter.java
  src/main/resources/static/index.html
  src/test/java/com/palettee/chat/ChatRedisServiceTest.java
  src/test/java/com/palettee/chat/ChatServiceTest.java
Labels: 📌 feature

#114 #85 - 채팅 관련된 이슈 총 정리
  src/main/java/com/palettee/chat/repository/ChatUserRepository.java
  src/main/java/com/palettee/chat/service/ChatUserService.java
  src/main/java/com/palettee/chat_room/controller/ChatRoomController.java
  src/main/java/com/palettee/chat_room/exception/DuplicateParticipationException.java
  src/main/java/com/palettee/chat_room/service/ChatRoomService.java
  src/main/java/com/palettee/global/configs/SecurityConfig.java
  src/main/java/com/palettee/global/configs/StompWebSocketConfig.java
  src/main/java/com/palettee/global/exception/ErrorCode.java
  src/main/java/com/palettee/global/handler/StompHandler.java
  src/main/java/com/palettee/global/handler/exception/ChatContentOverLength.java
  src/main/java/com/palettee/global/handler/exception/ChatImageOverNumber.java
Labels: 📂 refactor

#116 #115 - Fix/Enhance : 응답 데이터 추가 및 `아카이브 색상 통계` API 추가
  src/main/java/com/palettee/archive/repository/ArchiveRepository.java
  src/main/java/com/palettee/gathering/repository/GatheringRepositoryCustom.java
  src/main/java/com/palettee/gathering/repository/GatheringRepositoryImpl.java
  src/main/java/com/palettee/global/configs/SecurityConfig.java
  src/main/java/com/palettee/user/controller/UserController.java
  src/main/java/com/palettee/user/controller/dto/response/users/GatheringPagingDTO.java
  src/main/java/com/palettee/user/controller/dto/response/users/GetArchiveColorStatisticsResponse.java
  src/main/java/com/palettee/user/controller/dto/response/users/GetUserGatheringResponse.java
  src/main/java/com/palettee/user/controller/dto/response/users/SimpleArchiveInfo.java
  src/main/java/com/palettee/user/controller/dto/response/users/SimpleGatheringInfo.java
  src/main/java/com/palettee/user/service/UserService.java
  src/main/resources/logback-appender.xml
  src/test/java/com/palettee/user/controller/UserControllerTest.java
  src/test/java/com/palettee/user/service/UserServiceTest.java
Labels: 🖍 invalid, ✨ enhancement

#117 95 feat 게더링 수정사항 반영
  src/main/java/com/palettee/gathering/controller/GatheringController.java
  src/main/java/com/palettee/gathering/controller/dto/Response/GatheringDetailsResponse.java
  src/main/java/com/palettee/gathering/domain/Gathering.java
  src/main/java/com/palettee/gathering/repository/GatheringRepositoryImpl.java
  src/main/java/com/palettee/gathering/service/GatheringService.java
  src/main/java/com/palettee/global/configs/RedisConfig.java
  src/main/java/com/palettee/global/redis/service/RedisService.java
  src/main/java/com/palettee/global/scheduler/RedisScheduled.java
  src/main/java/com/palettee/likes/repository/LikeRepository.java
  src/main/java/com/palettee/portfolio/controller/PortFolioController.java
  src/main/java/com/palettee/portfolio/controller/dto/response/PortFolioResponse.java
  src/main/java/com/palettee/portfolio/domain/PortFolio.java
  src/main/java/com/palettee/portfolio/repository/PortFolioRepositoryImpl.java
  src/main/java/com/palettee/portfolio/service/PortFolioService.java
  src/main/java/com/palettee/user/service/BasicRegisterService.java
  src/main/resources/application-local.yml
  src/test/java/com/palettee/gathering/service/GatheringServiceTest.java
Labels: 📌 feature
