Repository prgrms-web-devcourse-final-project/WEB1_1_ZeroOne_BE, pull requests merged in 2024-11, with the labels that each got.

#7 #4 - Project 도메인 기본 코드 작성
  src/main/java/com/palettee/PaletteeApplication.java
  src/main/java/com/palettee/global/entity/BaseEntity.java
  src/main/java/com/palettee/project/domain/Project.java
  src/main/java/com/palettee/project/domain/ProjectImage.java
  src/main/java/com/palettee/project/domain/Tag.java
  src/main/java/com/palettee/project/repository/ProjectImageRepository.java
  src/main/java/com/palettee/project/repository/ProjectRepository.java
  src/main/java/com/palettee/project/repository/TagRepository.java
Labels: feature

#8 #9 - User 도메인 기본 코드 작성
  src/main/java/com/palettee/domain/Gathering.java
  src/main/java/com/palettee/domain/User.java
  src/main/java/com/palettee/repositories/GatheringRepository.java
  src/main/java/com/palettee/repositories/UserRepository.java
Labels: feature

#11 #5 - Chat 관련 Entity 생성
  src/main/java/com/palettee/chat/domain/Chat.java
  src/main/java/com/palettee/chat/repository/ChatRepository.java
  src/main/java/com/palettee/chat_room/domain/ChatCategory.java
  src/main/java/com/palettee/chat_room/domain/ChatRoom.java
  src/main/java/com/palettee/chat_room/repository/ChatRoomRepository.java
Labels: feature

#18 #16 - 성공 응답 및 예외 커스텀
  src/main/java/com/palettee/global/exception/ErrorCode.java
  src/main/java/com/palettee/global/exception/ErrorResponse.java
  src/main/java/com/palettee/global/exception/GlobalExceptionHandler.java
  src/main/java/com/palettee/global/exception/PaletteException.java
  src/main/java/com/palettee/global/success_response/SuccessResponse.java
  src/main/java/com/palettee/global/success_response/SuccessResponseAdvice.java
Labels: 📌 feature

#21 hotfix: `User` 에 `JobGroup` 분류 추가
  src/main/java/com/palettee/user/domain/MajorJobGroup.java
  src/main/java/com/palettee/user/domain/MinorJobGroup.java
  src/main/java/com/palettee/user/domain/User.java
Labels: 📌 feature

#20 Feat/#14 - `OAuth2` 로그인 기능과 `Jwt` 편의 기능 추가
  .github/workflows/ci-with-gradle-and-sonar.yml
  src/main/java/com/palettee/global/configs/SecurityConfig.java
  src/main/java/com/palettee/global/security/dto/GithubResponse.java
  src/main/java/com/palettee/global/security/dto/GoogleResponse.java
  src/main/java/com/palettee/global/security/dto/OAuth2Response.java
  src/main/java/com/palettee/global/security/jwt/CustomJwtUtil.java
  src/main/java/com/palettee/global/security/jwt/JwtUtils.java
  src/main/java/com/palettee/global/security/oauth/CustomOAuth2User.java
  src/main/java/com/palettee/global/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/palettee/global/security/oauth/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/palettee/global/security/oauth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/palettee/user/domain/User.java
  src/main/java/com/palettee/user/domain/UserRole.java
  src/main/java/com/palettee/user/repository/UserRepository.java
  src/main/resources/application.yml
Labels: 📌 feature

#24 #19 - 채팅방 관련 API 생성
  src/main/java/com/palettee/chat/domain/ChatUser.java
  src/main/java/com/palettee/chat/exception/ChatUserNotFoundException.java
  src/main/java/com/palettee/chat/repository/ChatUserRepository.java
  src/main/java/com/palettee/chat/service/ChatUserService.java
  src/main/java/com/palettee/chat_room/controller/ChatRoomController.java
  src/main/java/com/palettee/chat_room/controller/dto/request/ChatRoomCreateRequest.java
  src/main/java/com/palettee/chat_room/controller/dto/response/ChatRoomResponse.java
  src/main/java/com/palettee/chat_room/exception/ChatRoomNotFoundException.java
  src/main/java/com/palettee/chat_room/service/ChatRoomService.java
  src/main/java/com/palettee/global/exception/ErrorCode.java
Labels: 📌 feature

#26 #15 - 아카이브 관련 API 구현
  src/main/java/com/palettee/archive/controller/ArchiveController.java
  src/main/java/com/palettee/archive/controller/dto/request/ArchiveRegisterRequest.java
  src/main/java/com/palettee/archive/controller/dto/request/ArchiveUpdateRequest.java
  src/main/java/com/palettee/archive/controller/dto/request/ChangeOrderRequest.java
  src/main/java/com/palettee/archive/controller/dto/request/ImageUrlDto.java
  src/main/java/com/palettee/archive/controller/dto/request/TagDto.java
  src/main/java/com/palettee/archive/controller/dto/response/ArchiveDetailResponse.java
  src/main/java/com/palettee/archive/controller/dto/response/ArchiveListResponse.java
  src/main/java/com/palettee/archive/controller/dto/response/ArchiveResponse.java
  src/main/java/com/palettee/archive/controller/dto/response/ArchiveSimpleResponse.java
  src/main/java/com/palettee/archive/controller/dto/response/SliceInfo.java
  src/main/java/com/palettee/archive/domain/Archive.java
  src/main/java/com/palettee/archive/domain/ArchiveType.java
  src/main/java/com/palettee/archive/exception/ArchiveNotFound.java
  src/main/java/com/palettee/archive/repository/ArchiveCustomRepository.java
  src/main/java/com/palettee/archive/repository/ArchiveCustomRepositoryImpl.java
  src/main/java/com/palettee/archive/repository/ArchiveImageRepository.java
  src/main/java/com/palettee/archive/repository/ArchiveRepository.java
  src/main/java/com/palettee/archive/repository/CommentRepository.java
  src/main/java/com/palettee/archive/repository/TagRepository.java
  src/main/java/com/palettee/archive/service/ArchiveService.java
  src/main/java/com/palettee/global/configs/QueryDslConfig.java
  src/main/java/com/palettee/global/exception/ErrorCode.java
  src/main/java/com/palettee/likes/repository/LikeRepository.java
  src/main/java/com/palettee/user/domain/MajorJobGroup.java
  src/main/java/com/palettee/user/domain/MinorJobGroup.java
  src/main/java/com/palettee/user/domain/User.java
  src/main/java/com/palettee/user/repository/UserRepository.java
  src/test/java/com/palettee/archive/ArchiveServiceTest.java
Labels: 📌 feature

#27 #23 - `JwtFilter`, 토큰 API 추가
  .github/workflows/ci-with-gradle-and-sonar.yml
  build.gradle
  src/main/java/com/palettee/global/configs/RedisConfig.java
  src/main/java/com/palettee/global/configs/SecurityConfig.java
  src/main/java/com/palettee/global/configs/SwaggerConfig.java
  src/main/java/com/palettee/global/exception/ErrorCode.java
  src/main/java/com/palettee/global/redis/RedisService.java
  src/main/java/com/palettee/global/security/dto/oauth/GithubResponse.java
  src/main/java/com/palettee/global/security/dto/oauth/GoogleResponse.java
  src/main/java/com/palettee/global/security/dto/oauth/OAuth2FailureResponse.java
  src/main/java/com/palettee/global/security/dto/oauth/OAuth2Response.java
  src/main/java/com/palettee/global/security/dto/token/FilterExceptionResponse.java
  src/main/java/com/palettee/global/security/dto/token/TokenContainer.java
  src/main/java/com/palettee/global/security/dto/token/TokenIssueResponse.java
  src/main/java/com/palettee/global/security/jwt/controllers/TokenController.java
  src/main/java/com/palettee/global/security/jwt/exceptions/ExpiredTokenException.java
  src/main/java/com/palettee/global/security/jwt/exceptions/InvalidTokenException.java
  src/main/java/com/palettee/global/security/jwt/exceptions/NoTokenExistsException.java
  src/main/java/com/palettee/global/security/jwt/exceptions/NoUserFoundViaTokenException.java
  src/main/java/com/palettee/global/security/jwt/exceptions/RoleMismatchException.java
  src/main/java/com/palettee/global/security/jwt/filters/JwtExceptionHandlingFilter.java
  src/main/java/com/palettee/global/security/jwt/filters/JwtFilter.java
  src/main/java/com/palettee/global/security/jwt/handler/JwtAccessDeniedHandler.java
  src/main/java/com/palettee/global/security/jwt/services/TokenService.java
  src/main/java/com/palettee/global/security/jwt/utils/CustomJwtUtil.java
  src/main/java/com/palettee/global/security/jwt/utils/JwtUtils.java
  src/main/java/com/palettee/global/security/oauth/CustomOAuth2User.java
  src/main/java/com/palettee/global/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/palettee/global/security/oauth/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/palettee/global/security/oauth/handler/OAuth2LoginSuccessHandler.java
  src/main/resources/application.yml
  src/test/java/com/palettee/global/security/jwt/controllers/TokenControllerTest.java
  src/test/resources/application.yml
Labels: 📌 feature

#29 Test/Refactor - 테스트 코드 개선, 사소한 refactor
  src/main/java/com/palettee/global/security/jwt/services/RefreshTokenRedisService.java
  src/main/java/com/palettee/global/security/jwt/services/TokenService.java
  src/main/java/com/palettee/global/security/jwt/utils/CustomJwtUtil.java
  src/test/java/com/palettee/global/security/jwt/controllers/TokenControllerTest.java
  src/test/java/com/palettee/global/security/jwt/services/TokenServiceTest.java
Labels: ⛏ fix, 📂 refactor

#31 #28 - 아카이브 댓글 관련 API 구현
  src/main/java/com/palettee/archive/controller/ArchiveController.java
  src/main/java/com/palettee/archive/controller/dto/request/CommentWriteRequest.java
  src/main/java/com/palettee/archive/controller/dto/response/CommentDetail.java
  src/main/java/com/palettee/archive/controller/dto/response/CommentListResponse.java
  src/main/java/com/palettee/archive/controller/dto/response/CommentResponse.java
  src/main/java/com/palettee/archive/domain/Archive.java
  src/main/java/com/palettee/archive/domain/Comment.java
  src/main/java/com/palettee/archive/exception/CanNotCommentArchive.java
  src/main/java/com/palettee/archive/exception/CommentNotFound.java
  src/main/java/com/palettee/archive/exception/NotCommentOwner.java
  src/main/java/com/palettee/archive/repository/ArchiveCustomRepository.java
  src/main/java/com/palettee/archive/repository/ArchiveCustomRepositoryImpl.java
  src/main/java/com/palettee/archive/repository/CommentRepository.java
  src/main/java/com/palettee/archive/service/ArchiveService.java
  src/main/java/com/palettee/archive/service/CommentService.java
  src/main/java/com/palettee/global/exception/ErrorCode.java
  src/test/java/com/palettee/archive/ArchiveServiceTest.java
  src/test/java/com/palettee/archive/CommentServiceTest.java
Labels: 📌 feature

#35 #34 : `Enhance/Refactor` - `JwtFilter` 우회 `URI` 등록 방식 개선
  src/main/java/com/palettee/global/configs/SecurityConfig.java
  src/main/java/com/palettee/global/security/dto/GithubResponse.java
  src/main/java/com/palettee/global/security/dto/GoogleResponse.java
  src/main/java/com/palettee/global/security/dto/OAuth2Response.java
  src/main/java/com/palettee/global/security/dto/oauth/OAuth2FailureResponse.java
  src/main/java/com/palettee/global/security/dto/token/FilterExceptionResponse.java
  src/main/java/com/palettee/global/security/jwt/filters/JwtExceptionHandlingFilter.java
  src/main/java/com/palettee/global/security/jwt/filters/JwtFilter.java
  src/main/java/com/palettee/global/security/jwt/handler/JwtAccessDeniedHandler.java
  src/main/java/com/palettee/global/security/jwt/utils/BypassUrlHolder.java
  src/main/java/com/palettee/global/security/oauth/handler/OAuth2LoginFailureHandler.java
  src/test/java/com/palettee/global/security/jwt/controllers/TokenControllerTest.java
  src/test/java/com/palettee/global/security/jwt/utils/BypassUrlHolderTest.java
Labels: 📂 refactor, ✨ enhancement

#37 #25 - 웹소켓 채팅 기능 추가
  src/main/java/com/palettee/chat/controller/ChatController.java
  src/main/java/com/palettee/chat/controller/ChatImageController.java
  src/main/java/com/palettee/chat/controller/dto/request/ChatImgRequest.java
  src/main/java/com/palettee/chat/controller/dto/request/ChatImgUrlRequest.java
  src/main/java/com/palettee/chat/controller/dto/request/ChatRequest.java
  src/main/java/com/palettee/chat/controller/dto/response/ChatImgResponse.java
  src/main/java/com/palettee/chat/controller/dto/response/ChatImgUploadResponse.java
  src/main/java/com/palettee/chat/controller/dto/response/ChatImgUrlResponse.java
  src/main/java/com/palettee/chat/controller/dto/response/ChatResponse.java
  src/main/java/com/palettee/chat/domain/Chat.java
  src/main/java/com/palettee/chat/domain/ChatImage.java
  src/main/java/com/palettee/chat/service/ChatImageService.java
  src/main/java/com/palettee/chat/service/ChatService.java
  src/main/java/com/palettee/chat_room/service/ChatRoomService.java
  src/main/java/com/palettee/global/configs/S3Config.java
  src/main/java/com/palettee/global/configs/SecurityConfig.java
  src/main/java/com/palettee/global/configs/StompWebSocketConfig.java
  src/main/java/com/palettee/global/exception/ErrorCode.java
  src/main/java/com/palettee/global/handler/StompHandler.java
  src/main/java/com/palettee/global/handler/WebSocketErrorHandler.java
  src/main/java/com/palettee/global/handler/exception/WrongSubPathException.java
  src/main/java/com/palettee/global/s3/domain/FileExtension.java
  src/main/java/com/palettee/global/s3/exception/BadFileExtensionException.java
  src/main/java/com/palettee/global/s3/exception/FileEmptyException.java
  src/main/java/com/palettee/global/s3/exception/FileUploadFailException.java
  src/main/java/com/palettee/global/s3/service/ImageService.java
  src/main/java/com/palettee/global/security/jwt/utils/CustomJwtUtil.java
  src/main/java/com/palettee/global/security/jwt/utils/JwtUtils.java
  src/main/resources/static/index.html
  src/test/java/com/palettee/chat/ChatServiceTest.java
  src/test/java/com/palettee/global/s3/ImageServiceTest.java
Labels: 📌 feature

#39 #32 - `User` API 일부 추가
  src/main/java/com/palettee/archive/service/ArchiveService.java
  src/main/java/com/palettee/global/exception/ErrorCode.java
  src/main/java/com/palettee/global/security/jwt/filters/JwtFilter.java
  src/main/java/com/palettee/global/security/jwt/utils/BypassUrlHolder.java
  src/main/java/com/palettee/portfolio/repository/PortFolioRepository.java
  src/main/java/com/palettee/user/controller/BasicRegisterController.java
  src/main/java/com/palettee/user/controller/dto/request/RegisterBasicInfoRequest.java
  src/main/java/com/palettee/user/controller/dto/request/RegisterPortfolioRequest.java
  src/main/java/com/palettee/user/controller/dto/response/BasicInfoResponse.java
  src/main/java/com/palettee/user/controller/dto/response/UserResponse.java
  src/main/java/com/palettee/user/domain/Division.java
  src/main/java/com/palettee/user/domain/MajorJobGroup.java
  src/main/java/com/palettee/user/domain/MinorJobGroup.java
  src/main/java/com/palettee/user/domain/RelatedLink.java
  src/main/java/com/palettee/user/domain/User.java
  src/main/java/com/palettee/user/domain/UserRole.java
  src/main/java/com/palettee/user/exception/InvalidDivisionException.java
  src/main/java/com/palettee/user/exception/InvalidJobGroupException.java
  src/main/java/com/palettee/user/exception/JobGroupMismatchException.java
  src/main/java/com/palettee/user/repository/RelatedLinkRepository.java
  src/main/java/com/palettee/user/repository/UserRepository.java
  src/main/java/com/palettee/user/service/BasicRegisterService.java
  src/main/resources/application-local.yml
  src/test/java/com/palettee/archive/ArchiveServiceTest.java
  src/test/java/com/palettee/user/controller/BasicRegisterControllerTest.java
  src/test/java/com/palettee/user/service/BasicRegisterServiceTest.java
Labels: 📌 feature

#38 33 feature 게더링 crud
  src/main/java/com/palettee/gathering/Gathering.java
  src/main/java/com/palettee/gathering/GatheringNotFoundException.java
  src/main/java/com/palettee/gathering/GatheringRepository.java
  src/main/java/com/palettee/gathering/controller/GatheringController.java
  src/main/java/com/palettee/gathering/controller/dto/Request/GatheringCommonRequest.java
  src/main/java/com/palettee/gathering/controller/dto/Response/GatheringCommonResponse.java
  src/main/java/com/palettee/gathering/controller/dto/Response/GatheringDetailsResponse.java
  src/main/java/com/palettee/gathering/controller/dto/Response/GatheringLikeResponse.java
  src/main/java/com/palettee/gathering/controller/dto/Response/GatheringResponse.java
  src/main/java/com/palettee/gathering/domain/Contact.java
  src/main/java/com/palettee/gathering/domain/Gathering.java
  src/main/java/com/palettee/gathering/domain/GatheringTag.java
  src/main/java/com/palettee/gathering/domain/Position.java
  src/main/java/com/palettee/gathering/domain/Sort.java
  src/main/java/com/palettee/gathering/domain/Status.java
  src/main/java/com/palettee/gathering/domain/Subject.java
  src/main/java/com/palettee/gathering/repository/GatheringRepository.java
  src/main/java/com/palettee/gathering/repository/GatheringRepositoryCustom.java
  src/main/java/com/palettee/gathering/repository/GatheringRepositoryImpl.java
  src/main/java/com/palettee/gathering/repository/GatheringTagRepository.java
  src/main/java/com/palettee/gathering/service/GatheringService.java
  src/main/java/com/palettee/global/exception/ErrorCode.java
  src/main/java/com/palettee/global/exception/InvalidCategoryException.java
  src/main/java/com/palettee/likes/repository/LikeRepository.java
  src/main/java/com/palettee/portfolio/controller/PortFolioController.java
  src/main/java/com/palettee/portfolio/repository/PortFolioRepositoryImpl.java
  src/main/java/com/palettee/portfolio/service/PortFolioService.java
  src/main/java/com/palettee/user/domain/User.java
  src/main/java/com/palettee/user/exception/UserAccessException.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/java/com/palettee/gathering/service/GatheringServiceTest.java
  src/test/resources/application.yml
Labels: 📌 feature

#43 #42 - 사진 업로드 API 통일
  src/main/java/com/palettee/chat/controller/ChatImageController.java
  src/main/java/com/palettee/chat/controller/dto/response/ChatImgUploadResponse.java
  src/main/java/com/palettee/chat/service/ChatImageService.java
  src/main/java/com/palettee/global/exception/ErrorCode.java
  src/main/java/com/palettee/global/s3/controller/ImageController.java
  src/main/java/com/palettee/global/s3/controller/dto/response/ImageUrlResponse.java
  src/main/java/com/palettee/global/s3/controller/dto/response/ImagesResponse.java
  src/main/java/com/palettee/global/s3/service/ImageService.java
Labels: ⛏ fix

#40 ci: `QDomains`, 잡다한 파일들 `Test coverage` 에서 제외
  build.gradle
Labels: ✨ enhancement

#49 #48 Hotfix - 유저 프로필 이미지 `URL` `DB` 저장 추가
  src/main/java/com/palettee/user/controller/dto/request/RegisterBasicInfoRequest.java
  src/main/java/com/palettee/user/domain/StoredProfileImageUrl.java
  src/main/java/com/palettee/user/domain/User.java
  src/main/java/com/palettee/user/repository/StoredProfileImageUrlRepository.java
  src/main/java/com/palettee/user/service/BasicRegisterService.java
  src/test/java/com/palettee/user/controller/BasicRegisterControllerTest.java
  src/test/java/com/palettee/user/service/BasicRegisterServiceTest.java
Labels: ⛏ fix

#50 #41 - redis pub/sub 외부 메세지 브로커 사용
  build.gradle
  src/main/java/com/palettee/chat/controller/ChatController.java
  src/main/java/com/palettee/chat/controller/dto/request/ChatImgRequest.java
  src/main/java/com/palettee/chat/controller/dto/request/ChatRequest.java
  src/main/java/com/palettee/chat/controller/dto/response/ChatImgResponse.java
  src/main/java/com/palettee/chat/controller/dto/response/ChatImgUrlResponse.java
  src/main/java/com/palettee/chat/controller/dto/response/ChatResponse.java
  src/main/java/com/palettee/chat/service/ChatService.java
  src/main/java/com/palettee/global/configs/RedisConfig.java
  src/main/java/com/palettee/global/exception/ErrorCode.java
  src/main/java/com/palettee/global/handler/StompHandler.java
  src/main/java/com/palettee/global/handler/exception/ChatContentNullException.java
  src/main/java/com/palettee/global/handler/exception/JSONMappingException.java
  src/main/java/com/palettee/global/redis/pub/RedisPublisher.java
  src/main/java/com/palettee/global/redis/sub/RedisSubscriber.java
  src/main/resources/static/index.html
  src/test/java/com/palettee/chat/ChatServiceTest.java
Labels: 📌 feature

#47 #36 - SSE 기반 알림 구현
  src/main/java/com/palettee/archive/controller/ArchiveController.java
  src/main/java/com/palettee/archive/service/ArchiveService.java
  src/main/java/com/palettee/chat_room/controller/dto/request/ChatRoomCreateRequest.java
  src/main/java/com/palettee/chat_room/service/ChatRoomService.java
  src/main/java/com/palettee/gathering/service/GatheringService.java
  src/main/java/com/palettee/global/configs/AsyncConfig.java
  src/main/java/com/palettee/global/configs/SecurityConfig.java
  src/main/java/com/palettee/global/exception/ErrorCode.java
  src/main/java/com/palettee/notification/controller/NotificationController.java
  src/main/java/com/palettee/notification/controller/dto/NotificationDetailResponse.java
  src/main/java/com/palettee/notification/controller/dto/NotificationListResponse.java
  src/main/java/com/palettee/notification/controller/dto/NotificationRequest.java
  src/main/java/com/palettee/notification/domain/AlertType.java
  src/main/java/com/palettee/notification/domain/Notification.java
  src/main/java/com/palettee/notification/exception/NotMyNotification.java
  src/main/java/com/palettee/notification/exception/NotValidType.java
  src/main/java/com/palettee/notification/exception/NotificationNotFound.java
  src/main/java/com/palettee/notification/repository/EmitterRepository.java
  src/main/java/com/palettee/notification/repository/NotificationRepository.java
  src/main/java/com/palettee/notification/service/NotificationService.java
  src/main/java/com/palettee/portfolio/service/PortFolioService.java
  src/main/java/com/palettee/user/repository/UserRepository.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: 📌 feature

#52 #32 - `[Feat]` `User` API 완성
  src/main/java/com/palettee/archive/repository/ArchiveCustomRepository.java
  src/main/java/com/palettee/archive/repository/ArchiveCustomRepositoryImpl.java
  src/main/java/com/palettee/gathering/repository/GatheringRepositoryCustom.java
  src/main/java/com/palettee/gathering/repository/GatheringRepositoryImpl.java
  src/main/java/com/palettee/global/configs/SecurityConfig.java
  src/main/java/com/palettee/global/exception/ErrorCode.java
  src/main/java/com/palettee/portfolio/repository/PortFolioRepository.java
  src/main/java/com/palettee/user/controller/UserController.java
  src/main/java/com/palettee/user/controller/dto/request/EditUserInfoRequest.java
  src/main/java/com/palettee/user/controller/dto/response/GetUserArchiveResponse.java
  src/main/java/com/palettee/user/controller/dto/response/GetUserGatheringResponse.java
  src/main/java/com/palettee/user/controller/dto/response/SimpleArchiveInfo.java
  src/main/java/com/palettee/user/controller/dto/response/SimpleGatheringInfo.java
  src/main/java/com/palettee/user/controller/dto/response/UserDetailResponse.java
  src/main/java/com/palettee/user/controller/dto/response/UserEditFormResponse.java
  src/main/java/com/palettee/user/domain/User.java
  src/main/java/com/palettee/user/exception/NotOwnUserException.java
  src/main/java/com/palettee/user/repository/RelatedLinkRepository.java
  src/main/java/com/palettee/user/service/BasicRegisterService.java
  src/main/java/com/palettee/user/service/UserService.java
  src/test/java/com/palettee/user/controller/BasicRegisterControllerTest.java
  src/test/java/com/palettee/user/controller/UserControllerTest.java
  src/test/java/com/palettee/user/service/UserServiceTest.java
Labels: 📌 feature
