Repository prgrms-web-devcourse-final-project/WEB1_1_ZeroOne_BE, pull requests merged in 2025-01, with the labels that each got.

#130 [docs] : 기본 README.md 구성
  README.md
  assets/images/examples/alarm-example-1.gif
  assets/images/examples/alarm-example-2.png
  assets/images/examples/chatting-example.png
  assets/images/examples/gathering-example-1.png
  assets/images/examples/gathering-example-2.png
  assets/images/examples/login-example.png
  assets/images/examples/popular-portfolio-example.png
  assets/images/palettee-portfolio-view.png
  assets/images/palettee-user-archive-view.png
  assets/images/palettee-user-gathering-view.png
  assets/images/tech/backend-architecture.png
  assets/images/tech/tech-stacks.png
Labels: 📑 documentation

#135 #125 - 채팅, 채팅방 관련 전체적인 로직 변경
  src/main/java/com/palettee/chat/controller/dto/response/ChatCustomResponse.java
  src/main/java/com/palettee/chat/domain/ChatUser.java
  src/main/java/com/palettee/chat/repository/ChatCustomRepositoryImpl.java
  src/main/java/com/palettee/chat/repository/ChatImageRepository.java
  src/main/java/com/palettee/chat/repository/ChatRepository.java
  src/main/java/com/palettee/chat/repository/ChatUserRepository.java
  src/main/java/com/palettee/chat/service/ChatImageService.java
  src/main/java/com/palettee/chat/service/ChatRedisService.java
  src/main/java/com/palettee/chat/service/ChatService.java
  src/main/java/com/palettee/chat/service/ChatUserService.java
  src/main/java/com/palettee/chat_room/controller/ChatRoomController.java
  src/main/java/com/palettee/chat_room/controller/dto/response/ChatRoomInfoResponse.java
  src/main/java/com/palettee/chat_room/controller/dto/response/ChatRoomListResponse.java
  src/main/java/com/palettee/chat_room/domain/ChatCategory.java
  src/main/java/com/palettee/chat_room/repository/ChatRoomRepository.java
  src/main/java/com/palettee/chat_room/service/ChatRoomService.java
  src/main/java/com/palettee/global/Const.java
  src/main/java/com/palettee/global/handler/StompHandler.java
  src/test/java/com/palettee/chat/ChatRedisServiceTest.java
Labels: 📌 feature, 📂 refactor

#134 #131 - 이미지 변경 추적 기능 추가
  src/main/java/com/palettee/PaletteApplication.java
  src/main/java/com/palettee/archive/controller/ArchiveController.java
  src/main/java/com/palettee/archive/controller/dto/response/ArchiveRedisResponse.java
  src/main/java/com/palettee/archive/controller/dto/response/ArchiveSimpleResponse.java
  src/main/java/com/palettee/archive/domain/Archive.java
  src/main/java/com/palettee/archive/domain/ArchiveImage.java
  src/main/java/com/palettee/archive/event/HitEventListener.java
  src/main/java/com/palettee/archive/repository/ArchiveCustomRepositoryImpl.java
  src/main/java/com/palettee/archive/repository/ArchiveImageRepository.java
  src/main/java/com/palettee/archive/repository/ArchiveRedisRepository.java
  src/main/java/com/palettee/archive/repository/ArchiveRepository.java
  src/main/java/com/palettee/archive/service/ArchiveScheduler.java
  src/main/java/com/palettee/archive/service/ArchiveService.java
  src/main/java/com/palettee/image/ContentType.java
  src/main/java/com/palettee/image/ImageProcessor.java
  src/main/java/com/palettee/image/event/ImageEventListener.java
  src/main/java/com/palettee/image/event/ImageProcessingEvent.java
  src/main/java/com/palettee/user/controller/dto/response/users/GetUserArchiveResponse.java
  src/main/java/com/palettee/user/controller/dto/response/users/SimpleArchiveInfo.java
  src/test/java/com/palettee/archive/ArchiveServiceTest.java
  src/test/java/com/palettee/user/service/UserServiceTest.java
Labels: 📌 feature

#128 127 feat 인기 포트폴리오 방식 변경
  src/main/java/com/palettee/gathering/controller/GatheringController.java
  src/main/java/com/palettee/gathering/controller/dto/Response/GatheringDetailsResponse.java
  src/main/java/com/palettee/gathering/controller/dto/Response/GatheringPopularResponse.java
  src/main/java/com/palettee/gathering/controller/dto/Response/GatheringResponse.java
  src/main/java/com/palettee/gathering/domain/Gathering.java
  src/main/java/com/palettee/gathering/repository/GatheringRedisRepository.java
  src/main/java/com/palettee/gathering/repository/GatheringRepository.java
  src/main/java/com/palettee/gathering/repository/GatheringRepositoryImpl.java
  src/main/java/com/palettee/gathering/service/GatheringService.java
  src/main/java/com/palettee/global/cache/MemoryCache.java
  src/main/java/com/palettee/global/cache/RedisWeightCache.java
  src/main/java/com/palettee/global/configs/RedisConfig.java
  src/main/java/com/palettee/global/configs/SecurityConfig.java
  src/main/java/com/palettee/global/redis/service/RedisService.java
  src/main/java/com/palettee/global/scheduler/RedisScheduled.java
  src/main/java/com/palettee/likes/repository/LikeRepository.java
  src/main/java/com/palettee/portfolio/controller/PortFolioController.java
  src/main/java/com/palettee/portfolio/controller/dto/response/PortFolioPopularResponse.java
  src/main/java/com/palettee/portfolio/controller/dto/response/PortFolioResponse.java
  src/main/java/com/palettee/portfolio/domain/PortFolio.java
  src/main/java/com/palettee/portfolio/repository/PortFolioRedisRepository.java
  src/main/java/com/palettee/portfolio/repository/PortFolioRepositoryImpl.java
  src/main/java/com/palettee/portfolio/service/CategoryRedisService.java
  src/main/java/com/palettee/portfolio/service/PortFolioRedisService.java
  src/main/java/com/palettee/portfolio/service/PortFolioService.java
  src/test/java/com/palettee/gathering/service/GatheringRedisTest.java
  src/test/java/com/palettee/gathering/service/GatheringServiceTest.java
  src/test/java/com/palettee/portfolio/service/PortFolioCacheServiceTest.java
  src/test/java/com/palettee/portfolio/service/PortFolioServiceTest.java
Labels: 📌 feature

#138 #137 - 채팅방 관련 예외 처리 추가
  src/main/java/com/palettee/chat/domain/ChatUser.java
  src/main/java/com/palettee/chat/repository/ChatUserRepository.java
  src/main/java/com/palettee/chat/service/ChatUserService.java
  src/main/java/com/palettee/chat_room/exception/DuplicateCreateException.java
  src/main/java/com/palettee/chat_room/exception/DuplicateLeaveException.java
  src/main/java/com/palettee/chat_room/repository/ChatRoomRepository.java
  src/main/java/com/palettee/chat_room/service/ChatRoomService.java
  src/main/java/com/palettee/global/exception/ErrorCode.java
  src/main/java/com/palettee/global/handler/StompHandler.java
Labels: 📌 feature

#146 #145 - websocket 연결 cors 에러 처리
  src/main/java/com/palettee/global/configs/CorsConfig.java
Labels: ⛏ fix
